# GoReleaser config for hy CLI
# https://goreleaser.com

version: 2

project_name: hy

before:
  hooks:
    - go mod tidy

builds:
  - id: hy
    main: .
    binary: hy
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

brews:
  - name: hy
    repository:
      owner: hypewell-ai
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://hypewell.ai"
    description: "CLI for Hypewell Studio"
    license: "Proprietary"
    install: |
      bin.install "hy"
    test: |
      system "#{bin}/hy", "version"
